### ISSUE TITLE
Latest NeoBundle breaks plugin installs

### ISSUE THREAD

**Issue by dustinfarris** [JarrodCTaylor/dotfiles#8]
neobundle.vim changed how plugins are specified and it doesn't seem to work well here.

https://github.com/Shougo/neobundle.vim/commit/fd15e35a7a7c4e84ae62981cfa529ae7cc382330

**Comment by dustinfarris** [comment]
Figured it out,

I had to wrap my own custom plugins in neobundle#begin/end and that had the effect of overriding the native plugins bundled with your repo.

Is there an easy way to augment the plugins list without modifying vimrc in my fork?

**Comment by JarrodCTaylor** [comment]
I will have to look into this more.  Is the current configuration incompatible with a new api in neobundle or was the problem only with plugins that you have added?

As for modifying the dotfiles they are built for that.  By leveraging the `custom-configs` directory you shouldn't have any need for forking this repo. You can have your own customizations which you can keep under version control that will plug directly into the dotfiles. Here is one example https://github.com/TayHobbs/dotfiles_custom_config

**Comment by JarrodCTaylor** [comment]
I was successfully able to update all the plugins then delete the bundle directory and let neobundle reinstall them all with no error.

**Comment by dustinfarris** [comment]
The problem is when you have additional plugins in custom-configs.

I had to add the `neobundle#begin/end` to my vimrc here: https://github.com/dustinfarris/dotfiles-custom-configs/blob/master/vimrc.vim#L1-L10

When I do that, suddenly the native plugins in dotfiles are ignored—I lose unite, startify, etc.

**Comment by JarrodCTaylor** [comment]
You don't need to do that in order to add plugins. Follow the instructions in the README for adding plugins https://github.com/JarrodCTaylor/dotfiles#customizing-vim. 

If you want to add a plugin named `magic-foo` from `https://github.com/JarrodCTaylor/magin-foo` you could copy https://github.com/JarrodCTaylor/dotfiles/blob/master/vim/plugin-configs/tagbar.vim to your `custom-config` directory and rename it to `magic-foo-plugin.vim`  change line 4 to be `JarrodCTaylor/magin-foo` add key mappings and menu items as needed and then the plugin will be added automatically next time you open Vim.

**Comment by dustinfarris** [comment]
Nice.  Should've read the docs first.

It's working beautifully now.

**Comment by JarrodCTaylor** [comment]
Good deal.
